### ISSUE TITLE
I can not use it with nim 1.4.2

### ISSUE THREAD

**Issue by the-man-with-a-golden-mind** [zielmicha/leveldb.nim#23]
Hello,
So, I have installed leveldb using nimble. 
I've put leveldb as a requirement into my nimble file. I've checked if nimble is trying to add it on the "build" process. 
Everything looks fine...but I am getting " Error: cannot open file: leveldb".
It is quite funny because in the path of the leveldb package I don't have sources. I have only "leveldb" binary (which is leveldbtool). 

What I can do with that? 

Nim: 1.4.2
OS: Ubuntu

Best, 

Michal

**Comment by xyb** [comment]
@the-man-with-a-golden-mind Hi, Michal, I don't known how you are using leveldb.nim, but there is an example that might help:
https://github.com/zielmicha/leveldb.nim/blob/master/tests/packagetest/src/packagetest.nim

I closed this issue, but if you have any more questions, please feel free to reopen it.
